### ISSUE TITLE
error: undefined symbol: __get_random_u32_below

### ISSUE THREAD

**Issue by DrakoDom** [smuellerDD/lrng#26]
Hello, it's Dominic again.

This time, with kernel v6.1.4, I'm getting the error pasted below...

```
ld.lld: error: undefined symbol: __get_random_u32_below
>>> referenced by vma.c
>>>               arch/x86/entry/vdso/vma.o:(arch_setup_additional_pages) in archive vmlinux.a
>>> referenced by clocksource.c
>>>               kernel/time/clocksource.o:(clocksource_verify_percpu) in archive vmlinux.a
>>> referenced by slub.c
>>>               mm/slub.o:(new_slab) in archive vmlinux.a
>>> referenced 24 more times
make[1]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
make: *** [Makefile:1236: vmlinux] Error 2
```

It looks like something related to https://github.com/smuellerDD/lrng/issues/25#issue-1523993547, since the error is similar. But I'm not sure how that's possible, as I'm using the latest patches from https://github.com/smuellerDD/lrng/tree/master/kernel_patches/v6.1.

Here is my kernel config: https://pastebin.com/bby6m0EJ

Thanks.

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Januar 2023, 00:29:07 CET schrieb Dominic Esposito:

Hi Dominic,

> Hello, it's Dominic again.
> 
> This time, with kernel v6.1.4, I'm getting the error pasted below...

See answer to issue 25 and use the patch in branch 6.1.

Ciao
Stephan

**Comment by DrakoDom** [comment]
I'm still getting the same error after taking the patches from `git clone -b 6.1 https://github.com/smuellerDD/lrng.git`. I made sure to use new kernel sources that haven't had any old LRNG patches applied to them.

Am I doing something wrong?

**Comment by smuellerDD** [comment]
Am Dienstag, 10. Januar 2023, 17:25:32 CET schrieb Dominic Esposito:

Hi Dominic,

> I'm still getting the same error after taking the patches from `git clone -b
> 6.1 https://github.com/smuellerDD/lrng.git`. I made sure to use new kernel
> sources that haven't had any old LRNG patches applied to them.
> 
> Am I doing something wrong?

Check that the following function is there: https://github.com/smuellerDD/
lrng/commit/6784a5dc08e7376583db2e99b257a7862ea9ce84

Ciao
Stephan

**Comment by DrakoDom** [comment]
When running the command `grep -ir "Taken directly from random.c" .` in the `lrng` folder, I get the output `./lrng_interface_aux.c:/* Taken directly from random.c */`.

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. Januar 2023, 06:58:51 CET schrieb Dominic Esposito:

Hi Dominic,

> When running the command `grep -ir "Taken directly from random.c" .` in the
> `lrng` folder, I get the output `./lrng_interface_aux.c:/* Taken directly
> from random.c */`.

This is the function that was added and should work. It compiles for me and 
others. Can you please check that this file is prperly conpiled?

Ciao
Stephan

**Comment by DrakoDom** [comment]
Something between kernel v6.1.3 and v6.1.4 is happening. When compiling v6.1.3 with the exact same config and patches as v6.1.4, everything compiles successfully.

Maybe this is something Gentoo specific? `sys-kernel/gentoo-sources` comes with many patches already applied.

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. Januar 2023, 07:45:08 CET schrieb Dominic Esposito:

Hi Dominic,

> Something between kernel v6.1.3 and v6.1.4 is happening. When compiling
> v6.1.3 with the exact same config and patches as v6.1.4, everything
> compiles successfully.
> 
> Maybe this is something Gentoo specific? `sys-kernel/gentoo-sources` comes
> with many patches already applied.

The offending patch requiring the symbol that you reported missing appeared 
with 6.1.4.

The question is why the implementation of the function you reported is present
is not compiled or not found during linking.

Ciao
Stephan

**Comment by DrakoDom** [comment]
How should I verify that `lrng_interface_aux.c` is compiling correctly? If you can give me a command or a file to check, I can give you the results.

Thanks.

**Comment by ptr1337** [comment]
@DrakoDom 

Please pull the patches from the master branch, under kernel-patches/v6.1

Actually the missing patch is not in the 6.1 branch, where you are pulling from it seems like.
https://github.com/smuellerDD/lrng/compare/6.1...master#diff-b4031cbcc17e799c967febbb81f642c2016b545b150f0b1356af80ad0ed06676R138-R150

Or take this one:
https://github.com/CachyOS/kernel-patches/blob/master/6.1/misc/0001-lrng.patch

It is working well with 6.1.4

**Comment by DrakoDom** [comment]
With the master branch patches I get the same error as I did with the 6.1 branch. The CachyOS patch gives me a different error though...

```
drivers/char/lrng/lrng_interface_random_kernel.c:87:6: error: conflicting types for 'add_hwgenerator_randomness'
void add_hwgenerator_randomness(const void *buffer, size_t count,
     ^
./include/linux/random.h:20:6: note: previous declaration is here
void add_hwgenerator_randomness(const void *buf, size_t len, size_t entropy);
     ^
1 error generated.
make[4]: *** [scripts/Makefile.build:250: drivers/char/lrng/lrng_interface_random_kernel.o] Error 1
make[3]: *** [scripts/Makefile.build:500: drivers/char/lrng] Error 2
make[2]: *** [scripts/Makefile.build:500: drivers/char] Error 2
make[2]: *** Waiting for unfinished jobs....
```

And at the end of compiling...

```
make[1]: *** [scripts/Makefile.build:500: drivers] Error 2
make: *** [Makefile:1992: .] Error 2
```

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. Januar 2023, 00:23:28 CET schrieb Dominic Esposito:

Hi Dominic,

> With the master branch patches I get the same error as I did with the 6.1
> branch. The CachyOS patch gives me a different error though...
> 
> ```
> drivers/char/lrng/lrng_interface_random_kernel.c:87:6: error: conflicting
> types for 'add_hwgenerator_randomness' void
> add_hwgenerator_randomness(const void *buffer, size_t count,
>      ^
> ./include/linux/random.h:20:6: note: previous declaration is here
> void add_hwgenerator_randomness(const void *buf, size_t len, size_t
> entropy); ^
> 1 error generated.
> make[4]: *** [scripts/Makefile.build:250:
> drivers/char/lrng/lrng_interface_random_kernel.o] Error 1 make[3]: ***
> [scripts/Makefile.build:500: drivers/char/lrng] Error 2 make[2]: ***
> [scripts/Makefile.build:500: drivers/char] Error 2
> make[2]: *** Waiting for unfinished jobs....
> ```
> 
> And at the end of compiling...
> 
> ```
> make[1]: *** [scripts/Makefile.build:500: drivers] Error 2
> make: *** [Makefile:1992: .] Error 2
> ```

Then it seems the patch cf20b6971564d5f091830bac2248187ceed1a49e in the LRNG 
master branch should help.

Ciao
Stephan

**Comment by DrakoDom** [comment]
After applying the updated patch from https://github.com/CachyOS/kernel-patches/commit/6cc56e040b6de7049e30d444000974257cd96ec8, everything is compiling properly, and is verified to be working with `cat /proc/lrng_type`

Is it possible that I'm applying the patches from the LRNG master branch incorrectly?

```
~> cp /usr/src/lrng/kernel-patches/v6.1/v48-00* /usr/src/linux/
~> cd /usr/src/linux
~> for i in v48-00*.patch; do patch -p1 < $i; done
```

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. Januar 2023, 17:18:36 CET schrieb Dominic Esposito:

Hi Dominic,

> After applying the updated patch from
> https://github.com/CachyOS/kernel-patches/commit/6cc56e040b6de7049e30d44400
> 0974257cd96ec8, everything is compiling properly, and is verified to be
> working with `cat /proc/lrng_type`
> 
> Is it possible that I'm applying the patches from the LRNG master branch
> incorrectly?
> 
> ```
> ~> cp /usr/src/lrng/kernel-patches/v6.1/v48-00* /usr/src/linux/
> ~> cd /usr/src/linux
> ~> for i in v48-00*.patch; do patch -p1 < $i; done
> ```

that looks good, but remember that the patches covering the 6.1.4 kernel and 
the other issue go on top of it.

Ciao
Stephan

**Comment by DrakoDom** [comment]
Since this issue is solved for me, and no one else is having this issue, I'll close the issue now.
